### ISSUE TITLE
Everything gets placed in an empty '/' directory on s3

### ISSUE THREAD

**Issue by nackjicholson** [PyFilesystem/s3fs#1]
I'm finding this package unusable because I can't control where files get placed.

```python
with open_fs('s3://my-bucket') as root_fs:
    with root_fs.open('foo.csv', 'wb') as output_file:
        output_file.write('foo,bar')
```

The file ends up at `s3://my-bucket//foo.csv` instead of `s3://my-bucket/foo.csv`

**Comment by willmcgugan** [comment]
Confirmed, I'll have a fix soon.

**Comment by willmcgugan** [comment]
There is a fix in master, if you would like to try it.

**Comment by nackjicholson** [comment]
Thank you, I will give it a try. Cheers!

**Comment by nackjicholson** [comment]
@willmcgugan I gave it a quick go with the alpha, and it worked as expected. Thanks much!
