### ISSUE TITLE
ModuleNotFoundError: No module named 's3_s3fs'

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/s3fs#16]
The very first example from the docs does not work:

```
>>> from s3_s3fs import s3FS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 's3_s3fs'
```

Same setup as in #15

**Comment by willmcgugan** [comment]
There was a typo in the readme I just fixed. The following should work.

```python
>>> from fs_s3fs import S3FS
```

Assuming you have installed `fs-s3fs`

**Comment by willmcgugan** [comment]
Updated the readme with an Installing section, because it wasn't clear.
