### ISSUE TITLE
Writing to S3 also writes **locally**, failing on large files due to local out-of-disk space

### ISSUE THREAD

**Issue by zevix** [PyFilesystem/s3fs#18]
Using:
```
fs = open_fs(u"s3://....")
f = fs.open(u"filename", "wb")
while (...):
    f.write(...)
```
Crashed after consuming all local disk space.

Need to have an option to work without local disk access

**Comment by willmcgugan** [comment]
Opening a file on an S3FS requires that a local copy be created, in order to simulate a regular file.

In v0.1.6 you can use the `getfile` method which can download the file without the intermediate temporary file. Or you can use `fs.copy` which should also be able to avoid the temporary file.
