### ISSUE TITLE
Looser requirements in setup.py

### ISSUE THREAD

**Issue by samuelsinayoko** [PyFilesystem/s3fs#2]
Hi, am starting to use PyFilesystem and S3FS and I like it. One issue I'm having however is that some of my applications require older versions of boto3 (1.4.0) and botocore (1.4.28). 
I've done some tests and it doesn't seem to be an issue with `fs_s3fs`, so I was wondering if you could relax the requirements rules and use for example
```
REQUIREMENTS = [
    "boto3>=1.4.0, <1.5",
    "fs>=2.0",
    "six>=1.10"
]
```

This is also more in line with https://blog.miguelgrinberg.com/post/the-package-dependency-blues 
Happy to submit a PR if that'd help.

**Comment by willmcgugan** [comment]
Yes, can do. I'd probably go with `boto3~=1.4` syntax though.

**Comment by samuelsinayoko** [comment]
Great, I suppose there's no difference between `boto3~=1.4` and `boto3>=1.4.0,<1.5` anyway.

**Comment by willmcgugan** [comment]
v0.1.3 has the relaxed Boto requirement.
