### ISSUE TITLE
ResourceNotFound exception on removetree

### ISSUE THREAD

**Issue by limx0** [PyFilesystem/s3fs#25]
`removetree` breaks when (presumably) boto cleans up a directory after all files have been deleted.

To replicate (I am using a local minio server to test against): 

```python 
bucket_name = 'test-bucket1'

from minio import Minio
m = Minio(
    endpoint=MINIO_ENDPOINT, access_key=MINIO_KEY, 
    secret_key=MINIO_SECRET, secure=False
)
m.make_bucket(bucket_name)

from fs_s3fs import S3FS
fs = S3FS(
    bucket_name=bucket_name, aws_access_key_id=MINIO_KEY,
    aws_secret_access_key=MINIO_SECRET, endpoint_url='http://' + MINIO_ENDPOINT
)

dr = fs.makedirs('data/hello')
with dr.openbin('world', 'w') as f:
    f.write(b'somedata')

fs.removetree('data')
```

which raises

```python
ResourceNotFound                          Traceback (most recent call last)
<ipython-input-9-8b5db24ca94e> in <module>()
----> 1 fs.removetree('data')

~/anaconda3/envs/dev/lib/python3.6/site-packages/fs/base.py in removetree(self, dir_path)
   1057             for _path, info in gen_info:
   1058                 if info.is_dir:
-> 1059                     self.removedir(_path)
   1060                 else:
   1061                     self.remove(_path)

~/anaconda3/envs/dev/lib/python3.6/site-packages/fs_s3fs/_s3fs.py in removedir(self, path)
    636         if _path == '/':
    637             raise errors.RemoveRootError()
--> 638         info = self.getinfo(_path)
    639         if not info.is_dir:
    640             raise errors.DirectoryExpected(path)

~/anaconda3/envs/dev/lib/python3.6/site-packages/fs_s3fs/_s3fs.py in getinfo(self, path, namespaces)
    433                     obj.load()
    434         except errors.ResourceNotFound:
--> 435             raise errors.ResourceNotFound(path)
    436 
    437         if _path == '/':

ResourceNotFound: resource '/data/hello' not found
```

I assume that boto is cleaning up the directory after all files have been deleted. In which case we probably want to do something in `removedir` like

```python
try:
    info = self.getinfo(_path)
except ResourceNotFound:
    return
```

Thoughts?

**Comment by willmcgugan** [comment]
I can't replicate that with AWS. What versions of S3FS / FS / Boto do you have installed?

**Comment by limx0** [comment]
If you run the test I've added in #26 against AWS, it works ?

**Comment by limx0** [comment]
I'm on 
```
boto3==1.5.31
botocore==1.8.45
fs==2.0.18
fs-s3fs==0.1.7
```

**Comment by willmcgugan** [comment]
I'm on

```
boto3==1.5.22
botocore==1.8.36
fs==2.0.19a0
fs-s3fs==0.1.7
```

And your test works for me, without your patch.

Curious. I will try upgrading my boto to your version.

**Comment by willmcgugan** [comment]
Still works. Has to be an issue with Minio. I'll try it against Minio locally.

**Comment by willmcgugan** [comment]
Ok, confirmed. Failed with Minio.

I ran the test suite against a local Minio server, and there were a number of fails. This tells me that Minio doesn't quite replicate AWS. The issue you found is one of several.

I'm a little hesitant to attempt to fix them, because I don't want a situation where I break AWS in order to get Minio working.

I think I'm going to reluctantly make this a 'wontfix' bug. Unless its sponsored, it would just be too much work to justify right now.

**Comment by limx0** [comment]
Appreciate you actually checking that @willmcgugan. I will follow up an issue with Minio.

**Comment by frthjf** [comment]
@limx0 Have you followed up with Minio? Otherwise I'd raise an issue
