### ISSUE TITLE
Cache-Control header

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/s3fs#32]
Hi,

Is there any way to set additional headers when uploading files? Such as the 'Cache-Control' header?

I'm uploading images, and have to modify the headers afterwards, thus making at least 2 calls. 

Thanks in advance,

Geoff

**Comment by willmcgugan** [comment]
There isn't at the moment. Open to suggestions about how to add that to the api...

**Comment by geoffjukes** [comment]
I don't think it's unreasonable to set something like `upload_args` and `download_args` after instantiating the filesystem object.

That would be compatible with all the 'copy' methods, would not require changes to any other modules. and (neatly, I think) apply the same options to all uploads/downloads for the lifetime of the filesystem instance.

According to [the docs](https://boto3.readthedocs.io/en/latest/reference/customizations/s3.html#boto3.s3.transfer.S3Transfer.ALLOWED_UPLOAD_ARGS) you can use `extra_args` for uploads (setting ACLs, cache control, metadata, and a ton more) and also on Downloads (for server-side encryption keys). So a small change would activate a ton of flexibility :)

```
import fs
with fs.open_fs('s3://bucket/') as bucket:
  bucket.upload_args = {"CacheControl": "max-age=2592000", "ACL": "public-read"}
  fs.copy.copyfile('/path/to', 'file.ext', bucket, 'file.ext')
```
I'm not attached to this method, but I do see a certain elegance in it.
I'll put in a pull request with the changes.
