### ISSUE TITLE
support Google Cloud Storage explicitly

### ISSUE THREAD

**Issue by tmbdev** [PyFilesystem/s3fs#34]
Google Cloud Storage uses the same protocol as S3 but a different API endpoint and different prefix (gs: vs s3:). It would be convenient if s3fs included the Google endpoint and prefix so that it can work with both object storage systems.

See here: https://cloud.google.com/storage/docs/interoperability

Request endpoints: https://cloud.google.com/storage/docs/request-endpoints

Example endpoint: www.googleapis.com/storage/v1/[PATH_TO_RESOURCE]

**Comment by geoffjukes** [comment]
Hi @tmbdev,

The GCS API isn't 100% S3 compatible (if I recall correctly), and I'm pretty sure it breaks in S3FS because Boto3 uses Multi-Part uploads for larger files, and the GCS API doesn't support that. It works just fine for small files, but not all GCS features are supported.

(See https://github.com/PyFilesystem/pyfilesystem2/issues/147)

You can enable this using S3FS as-is, using the `endpoint_url` option. For example:

```
s3://BUCKET_KEY:BUCKET_SECRET@BUCKET_NAME/optional/path/to/directory?endpoint_url=https://www.googleapis.com
```

(I do this to write to Wasabi storage, which is 100% S3 compatible)

@willmcgugan - Do you think it makes more sense to implement a new filesystem that supports GCS 'fully', rather than shoe-horn it into S3FS?

**Comment by willmcgugan** [comment]
@geoffjukes Potentially, yeah. It might be possible to factor out a common base class to avoid duplication of effort.

**Comment by birnbaum** [comment]
I'm currently working on a basic GCS implementation based on [google-cloud-storage](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/storage).

This repository is a great help and for sure the two implementations share a lot of code. Unfortunately the APIs of boto3 and google-cloud-storage are pretty different, also regarding the controll flow (boto3 throws a lot of exceptions while google-cloud-storage woud e.g. just return None if an object does not exist). 

As we need a first version at work asap, I will continue "the dirty way" and alter your codebase until I have a working implementation. If everything works as expected we of course want to open source it and we may think of factoring out a common base.

Just dropping this comment here in case anyone is already working on the same thing.

**Comment by birnbaum** [comment]
A first version is done 🙂 I'm truely amazed by the API and documentation of this framework, it took less than two days to understand the concepts and write a basic GCS implementation which passes all unit tests. You did a really great work!

We will now integrate this first version in our company internal code base and I'll try to further improve it. I will push towards open sourcing it asap but there is a lot on our to-do list and I'll be on vacation soon so this will for sure be several weeks from now.

**Comment by willmcgugan** [comment]
Fantastic. Keep me posted :-)

**Comment by rabernat** [comment]
Any updates on this? Would be great to have a pyfilesystem that uses the native google api.

**Comment by birnbaum** [comment]
The filesystem is functional and we already use it in all production systems. I'm pushing to open source it and it will happen soon, but there is still some work to do as it is the first OS project of this company. I'll keep you posted, I think you can expect a release in the next 2-3 weeks :)

**Comment by willmcgugan** [comment]
@rkhwaja has released a google drive fs. https://github.com/rkhwaja/fs.googledrivefs

**Comment by birnbaum** [comment]
Hey guys, thanks for your patience! GCSFS is finally open-sourced 🙂https://github.com/Othoz/gcsfs

There are still many things on my TODO list, but for 90% of all use-cases it should be good to go. Any feedback is welcome!

**Comment by willmcgugan** [comment]
Amazing, thanks @birnbaum And Othoz!

I've added fs-gcfs to https://www.pyfilesystem.org/page/index-of-filesystems/

I guess I can also close this ticket. :-)
