### ISSUE TITLE
Encryption option for makedir()

### ISSUE THREAD

**Issue by julillae** [PyFilesystem/s3fs#36]
Hello!

Would it be possible to extend the current support for encryption options to makedir() in the S3FS class?

I was excited to be able to use upload_args to pass server side encryption options for file uploads to an s3 bucket. It works fine for file uploads. However, I am unable to create a directory in an s3 bucket that has an encryption policy. Looking at the code, I think that the upload_args are not passed to s3 in makedir() as they are when files are created. I know a directory is essentially a dummy file as far as s3 is concerned but, as I am using PyFilesystem to leverage the abstraction, I'd like to continue to use makedir() in my code (i.e. to make it easier to swap different storage backends in and out). 

Thanks for the consideration!

**Comment by willmcgugan** [comment]
Sounds reasonable. @geoffjukes any thoughts?

**Comment by geoffjukes** [comment]
I’m away for a week, but assuming nobody else puts in a PR before I get back, I don’t see any issue with this @willmcgugan. 

@julillae I hadn’t actually considered this use-case (a bucket policy that requires objects be encrypted)

**Comment by geoffjukes** [comment]
@willmcgugan This should be as simple as modifying https://github.com/PyFilesystem/s3fs/blob/6d04cd1633495329a6fa02d02bd8e5cb057e143f/fs_s3fs/_s3fs.py#L538

```
self.s3.Object(self._bucket_name, _key).put()
```
to
```
self.s3.Object(self._bucket_name, _key).put(**self._upload_args(_key))
```
The `Object().put()` takes the kwargs defined in the `ExtraArgs` dict.

**Comment by willmcgugan** [comment]
That change is in 0.1.9.

Thanks @geoffjukes 

@julillae Let me know if that hasn't fixed your issue.
