### ISSUE TITLE
botocore.vendored.requests.packages.urllib3.connectionpool: Resetting dropped connection: my-bucket.s3.us-west-2.amazonaws.com

### ISSUE THREAD

**Issue by fredmajor** [PyFilesystem/s3fs#41]
Hi,
when reading files from S3, I see a lot of messages like the one in the subject line.
Can anybody explain what that means and if this is something I should worry about?

**Comment by willmcgugan** [comment]
I haven't seen that myself. How have you got logging configured?

**Comment by fredmajor** [comment]
Info. Another thing is that I do a lot of walking across large amounts of small files, e.g.:
```python
def extract_txts_from_location(root_path):
    with open_fs(root_path) as fs:
        for file_path in fs.walk.files(filter=['*.txt']):
            file_opener = _get_opener(file_path, fs)
            with file_opener(file_path) as opened_file:
                yield from _extract_txt(opened_file, file_path)
```

```python
def configure_logging():
    mondrian.setup(excepthook=True)
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    etl_log_path = get_etl_log_path()

    if not os.path.exists(etl_log_path):
        os.makedirs(etl_log_path)

    fh = logging.FileHandler(os.path.join(etl_log_path, 'etl_jobs.log'))
    fh.setLevel(logging.DEBUG)
    fmt = '%(levelname)s:%(asctime)s:%(name)s: %(message)s'
    file_formatter = logging.Formatter(fmt)
    fh.setFormatter(file_formatter)
    logger.handlers[0].setFormatter(file_formatter)
    logger.addHandler(fh)
    return logger
```

**Comment by willmcgugan** [comment]
I suspect its benign, assuming it's working otherwise? It's coming from boto, so it's unlikely to be an issue with S3FS. Do you have any proxy between you and Amazon?

BTW, if you are working with a lot of small files, you will likely get better performance by disabling strict mode.

**Comment by willmcgugan** [comment]
If strict is enabled (default), S3FS will follow the PyFilesystem spec exactly. If strict mode is disabled it will omit a few checks in the interest of performance. The main one is attempting to open a path that is a directory, which normally requires an additional request to determine. 

Generally you will have done a scan dir before opening a file, so you know in advance a path is file and not a directory. So its safe to disable strict mode.

Going to close this issue, but feel free to re-open if you find think that warning could be fixed in S3FS.

**Comment by fredmajor** [comment]
@willmcgugan thanks a lot! I will try disabling the strict mode.

**Comment by fredmajor** [comment]
@willmcgugan one more question here - how am I supposed to disable the strict mode? I don't construct the S3FS manually, I use fs.open_fs

**Comment by willmcgugan** [comment]
Add `?strict=0` to the FS URL.

It's relatively new, docs haven't caught up yet...

**Comment by fredmajor** [comment]
@willmcgugan thank you, I will give it a shot!
