### ISSUE TITLE
s3fs incompatible with latest fs

### ISSUE THREAD

**Issue by Spacerat** [PyFilesystem/s3fs#42]
The latest version of pyfilesystem2 [is 2.1.0](https://github.com/PyFilesystem/pyfilesystem2/blob/9e4d4b906893b321571fb64896d647e8451d520b/fs/_version.py), but s3fs [requires ~2.0.18](https://github.com/PyFilesystem/s3fs/blob/17605168bb1b9d65402c59010afa67d4bdd941e7/setup.py#L27). Is there a specific reason for this, or could this constraint be relaxed?

**Comment by willmcgugan** [comment]
There's a new release coming shortly, with the most up to date PyFilesystem.

**Comment by willmcgugan** [comment]
Version 1.0.0 is in Pypi now. No material changes from previous version apart from dependancies.

**Comment by Spacerat** [comment]
Great - thanks for letting me know!
