### ISSUE TITLE
Makedirs fails against vanilla minio instance

### ISSUE THREAD

**Issue by mhworth** [PyFilesystem/s3fs#46]
If I have a minio server running like this:

`docker run -e "MINIO_ACCESS_KEY=test" -e "MINIO_SECRET_KEY=password" -p 9001:9000 minio/minio server /data`

Then the following simple example fails:

```python 
from fs_s3fs import S3FS

MINIO_URL = "http://localhost:9001"
s3fs = S3FS('scratch', endpoint_url=MINIO_URL,
         aws_access_key_id="test",
         aws_secret_access_key="password")

s3fs.client.create_bucket(Bucket="scratch")
s3fs.makedirs("test/object")
with s3fs.open("test/object/file.log", "w") as f:
    f.write("foo")
```

with the following error:

```
$ python test_s3fs.py
 ...
fs.errors.ResourceNotFound: resource 'test/object' not found
```
I traced it through and found that the problem is that the directories aren't being made when makedirs  is called, causing the recursive creation of directories to fail.

**Comment by frthjf** [comment]
I have the same issue

**Comment by willmcgugan** [comment]
Sorry, forgot about this issue. I'm afraid S3FS just doesn't work well with minio. More details here https://github.com/PyFilesystem/s3fs/issues/25

I'm willing to look at again if there is a new version of Minio, but at the moment I just can't support both S3 and Minio.

**Comment by mhworth** [comment]
Got it, thanks @willmcgugan !
