### ISSUE TITLE
Support for S3 compatible services

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/s3fs#6]
Hi,

I just found PyFilesystem - and I was half way through my own implementation of the same concept (I was about to write the ftp adapter). So I’m ditching my code, and using yours :) Thank you!

The only thing I’m not sure how to do (cleanly) is to use the s3fs adapter with an S3 compatible service, for example Swift/Ceph/Wasabi - specifically Wasabi in my case. 

In my implementation, I simply set the `endpoint_url` during the Boto3 client init. The rest was the same. 

Thoughts?

Many thanks,

Geoff

**Comment by willmcgugan** [comment]
Glad you found it useful!

I'll looking in to adding that `endpoint_url` to the constructor. Maybe also an environment variable specifying the endpoint url if not set expliciity?

**Comment by willmcgugan** [comment]
Hi Geoff,

I've added an `endpoint_url` parameter to the constructor in `0.1.4`. Wouldn't you mind giving that a try?

**Comment by geoffjukes** [comment]
Wow, that was quick Will, Thanks! I’ll give it a whirl at the office tomorrow, and let you know. 

Geoff

**Comment by geoffjukes** [comment]
@willmcgugan This works perfectly, when using the `S3FS` class. I've submitted a pull request to add `endpoint_url` to the opener, passed as a URL parameter, and a couple of additions to the README's.

Apologies in advance, I messed up the README.rst and reverted it, but couldn't 'undo' the commit from where I am, so the pull request is a bit ugly.

**Comment by willmcgugan** [comment]
Great. Will have a look at the PR.
