### ISSUE TITLE
AWS access key is not passed to S3 resource

### ISSUE THREAD

**Issue by genben** [PyFilesystem/s3fs#7]
The options `aws_access_key_id` and `aws_secret_access_key` are not passed to boto3.resource() function.

Below is a fix.

Original code (file `_s3fs.py`):

    @property
    def s3(self):
        if not hasattr(self._tlocal, 's3'):
            self._tlocal.s3 = boto3.resource('s3')
        return self._tlocal.s3

Solution:

    @property
    def s3(self):
        if not hasattr(self._tlocal, 's3'):
            self._tlocal.s3 = boto3.resource(
                's3',
                aws_access_key_id=self.aws_access_key_id,
                aws_secret_access_key=self.aws_secret_access_key,
                aws_session_token=self.aws_session_token
            )
        return self._tlocal.s3

**Comment by willmcgugan** [comment]
Thanks. Will have a fix soon.

**Comment by willmcgugan** [comment]
Should be fixed in 0.1.4

**Comment by genben** [comment]
Great! Thank you.
