### ISSUE TITLE
Optimize uploading to S3

### ISSUE THREAD

**Issue by genben** [PyFilesystem/s3fs#9]
Is it necessary to send `GET` request to S3 every time the file is uploaded? 

In methods `S3FS.setbinfile()` and `S3FS.setbytes()`, it sends two GET requests. First time, it checks if the the parent directory exists (calls `S3FS.isdir()`).  Second time, it checks if the URL is not a directory (calls `S3FS.getinfo()`).  

These operations are quite expensive. The effective upload speed increases at least x3 times when these methods are not called.

Here is the existing code:

    def setbinfile(self, path, file):
        _path = self.validatepath(path)
        _key = self._path_to_key(_path)

        if not self.isdir(dirname(path)):
            raise errors.ResourceNotFound(path)
        try:
            info = self.getinfo(path)
            if info.is_dir:
                raise errors.FileExpected(path)
        except errors.ResourceNotFound:
            pass

        with s3errors(path):
            self.client.upload_fileobj(file, self._bucket_name, _key)

Proposed solution:

    def setbinfile(self, path, file):
        _path = self.validatepath(path)
        _key = self._path_to_key(_path)

        with s3errors(path):
            self.client.upload_fileobj(file, self._bucket_name, _key)

And similar changes should be applied to `setbytes()` method.

**Comment by willmcgugan** [comment]
It is unfortunate, but in order to be a compliant implementation (and pass the [tests](https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/test.py)), it has to throw the same set of exceptions as all the other implementations. I'm open to suggestion regarding optimisations. I'd also consider api additions that didn't break old interfaces.

**Comment by genben** [comment]
Maybe, just introduce the additional option to S3FS contstructor, which would disable/enable such validation?
Something like `validate_dst_path=False` (need better name).
For backward compatibility, the validation can be enabled by default.

**Comment by willmcgugan** [comment]
That's an idea. How about `strict` which defaults to `True`, but would omit expensive validation if set to `False`.

**Comment by genben** [comment]
Yes. This name ("strict") is much better.

**Comment by genben** [comment]
I have made the mentioned changes to the forked repository: https://github.com/miarec/s3fs/commit/756aff38c56221e5d1278775eb6afced68d28b40

Probably, the comment could be improved.

**Comment by willmcgugan** [comment]
Looks good. Would you like to submit a PR for that? I'll get it in the next release.
